name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - main
    - release**
env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  RUN_REGION: us-central1
  SERVICE_NAME: helloworld-python
  GCP_PROJECT_ID_PREFIX: 'actiontest'

jobs:
  setup-build-deploy:
    name: "Setup, Build, and Deploy - '${{github.ref}}'"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/*-}" >> $GITHUB_ENV
    
    - name: Test
      run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}  
    # Setup gcloud CLI  
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.RUN_SA_KEY }}
        project_id: ${{ secrets.RUN_PROJECT }}

    # Build and push image to Google Container Registry  
    - name: Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/$PROJECT_ID/$SERVICE_NAME:devlatest4"
  
    #Terraform remote state GCS
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Terraform script checkout 
    - name: Terraform repository checkout 
      uses: actions/checkout@v2
      with:
        repository: prasadjblin/tf-store
        path: istudio-tf-scripts        
        ssh-strict: false
        #ssh-key: ${{ secrets.MGMT_SSH }}

    - name: Terraform init
      id: init
      run: terraform init
      continue-on-error: false
      working-directory: ./istudio-tf-scripts
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform Plan
      id: plan
      run: terraform plan
      continue-on-error: false
      working-directory: ./istudio-tf-scripts
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}   
    
    - name: Terraform apply
      id: apply
      run: terraform apply -auto-approve
      continue-on-error: false
      working-directory: ./istudio-tf-scripts
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 
    
    # provisioning and deploy from iStudio
    - name: iStudio provisioning
      continue-on-error: false
      run: |-
        curl -X POST http://istudio.thecloudbridge.net:5000/InfraCommand/acemicro@hcl.com/GCP/IkeaTrial/usecase2/install-infra \
             -d 'Client_Email=${{secrets.IS_CLIENT_EMAIL}}' \
             -d 'GCE_Project_Id=${{secrets.IS_GCE_PROJECT_ID}}' \
             -d 'GCE_Client_Id=${{secrets.IS_GCE_CLIENT_ID}}' \
             -d 'GCE_Private_Key_Id=${{secrets.IS_GCE_PRIVATE_KEY_ID}}' \
             -d 'GCE_Private_Key=${{secrets.IS_GCE_PRIVATE_KEY}}' \
             -d 'Client_Certificate_URL=${{secrets.IS_CLIENT_CERTIFICATE_URL}}'	
    
    #check service availability       
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.2
      with:
        # Check the following URLs one by one sequentially
        url: https://helloworld-python-5pwvjfrcgq-uc.a.run.app
        follow-redirect: no # Optional, defaults to "no"
        max-attempts: 3 # Optional, defaults to 1
        retry-delay: 5s # Optional, only applicable to max-attempts > 1
